# frozen_string_literal: true

module MuriloEduardo
  module VRayToolkit
    module Features
      module LayoutSheets

        # Translations for {I18n.t}.
        STRINGS = {
          'en' => {
            menu_item: 'LayOut Sheets from Scenes...',
            title: 'LayOut Sheets from Scenes',
            index_title: 'Sheet Index',
            sheet_number: 'Sheet %{number} / %{total}',
            date_format: '%Y-%m-%d',
            prompt_prefix: 'Scene name starts with (comma separated, empty = all)',
            prompt_paper: 'Paper',
            prompt_orientation: 'Orientation',
            prompt_render_mode: 'Viewport rendering',
            prompt_scale: 'Orthographic views scale',
            scale_auto: 'Automatic (fits the sheet)',
            scale_label: 'Scale %{scale}',
            prompt_index_sheet: 'Add sheet index',
            prompt_export_pdf: 'Also export PDF',
            orientation_landscape: 'Landscape',
            orientation_portrait: 'Portrait',
            render_mode_raster: 'Raster',
            render_mode_hybrid: 'Hybrid',
            render_mode_vector: 'Vector',
            answer_yes: 'Yes',
            answer_no: 'No',
            layout_unavailable: 'The LayOut API is not available in this SketchUp (it needs SketchUp Pro).',
            not_saved: 'Save the model first: LayOut viewports reference the saved .skp file.',
            save_changes: 'The model has unsaved changes. LayOut uses the saved file. Save it now?',
            no_scenes: 'The model has no scenes. Create scenes (View > Animation > Add Scene) first.',
            no_matching_scenes: 'No scene name starts with "%{prefix}".',
            done: "%{count} sheets created:\n%{layout}",
            done_pdf: 'PDF: %{pdf}',
            skipped: 'Skipped (not in the saved file, save the model and try again): %{scenes}',
          },
          'pt-BR' => {
            menu_item: 'Pranchas do LayOut por Cena...',
            title: 'Pranchas do LayOut por Cena',
            index_title: 'Índice de Pranchas',
            sheet_number: 'Prancha %{number} / %{total}',
            date_format: '%d/%m/%Y',
            prompt_prefix: 'Nome da cena começa com (separe por vírgula; vazio = todas)',
            prompt_paper: 'Papel',
            prompt_orientation: 'Orientação',
            prompt_render_mode: 'Renderização da viewport',
            prompt_scale: 'Escala das vistas ortogonais',
            scale_auto: 'Automática (cabe na prancha)',
            scale_label: 'Escala %{scale}',
            prompt_index_sheet: 'Incluir índice de pranchas',
            prompt_export_pdf: 'Exportar PDF também',
            orientation_landscape: 'Paisagem',
            orientation_portrait: 'Retrato',
            render_mode_raster: 'Raster',
            render_mode_hybrid: 'Híbrida',
            render_mode_vector: 'Vetorial',
            answer_yes: 'Sim',
            answer_no: 'Não',
            layout_unavailable: 'A API do LayOut não está disponível neste SketchUp (exige o SketchUp Pro).',
            not_saved: 'Salve o modelo antes: as viewports do LayOut apontam para o arquivo .skp salvo.',
            save_changes: 'O modelo tem alterações não salvas. O LayOut usa o arquivo salvo. Salvar agora?',
            no_scenes: 'O modelo não tem cenas. Crie cenas antes (Exibir > Animação > Adicionar cena).',
            no_matching_scenes: 'Nenhuma cena começa com "%{prefix}".',
            done: "%{count} pranchas criadas:\n%{layout}",
            done_pdf: 'PDF: %{pdf}',
            skipped: 'Puladas (não estão no arquivo salvo; salve o modelo e tente de novo): %{scenes}',
          },
          'es' => {
            menu_item: 'Láminas de LayOut por Escena...',
            title: 'Láminas de LayOut por Escena',
            index_title: 'Índice de Láminas',
            sheet_number: 'Lámina %{number} / %{total}',
            date_format: '%d/%m/%Y',
            prompt_prefix: 'El nombre de la escena empieza con (separe con comas; vacío = todas)',
            prompt_paper: 'Papel',
            prompt_orientation: 'Orientación',
            prompt_render_mode: 'Renderizado de la ventana',
            prompt_scale: 'Escala de las vistas ortogonales',
            scale_auto: 'Automática (cabe en la lámina)',
            scale_label: 'Escala %{scale}',
            prompt_index_sheet: 'Incluir índice de láminas',
            prompt_export_pdf: 'Exportar también a PDF',
            orientation_landscape: 'Horizontal',
            orientation_portrait: 'Vertical',
            render_mode_raster: 'Ráster',
            render_mode_hybrid: 'Híbrido',
            render_mode_vector: 'Vectorial',
            answer_yes: 'Sí',
            answer_no: 'No',
            layout_unavailable: 'La API de LayOut no está disponible en este SketchUp (requiere SketchUp Pro).',
            not_saved: 'Guarde el modelo primero: las ventanas de LayOut apuntan al archivo .skp guardado.',
            save_changes: 'El modelo tiene cambios sin guardar. LayOut usa el archivo guardado. ¿Guardar ahora?',
            no_scenes: 'El modelo no tiene escenas. Cree escenas primero (Ver > Animación > Agregar escena).',
            no_matching_scenes: 'Ninguna escena empieza con "%{prefix}".',
            done: "%{count} láminas creadas:\n%{layout}",
            done_pdf: 'PDF: %{pdf}',
            skipped: 'Omitidas (no están en el archivo guardado; guarde el modelo e intente de nuevo): %{scenes}',
          },
        }.freeze

      end
    end
  end
end
